blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Pangu-Immortal/KeepLiveService/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: Telegram Group
    url: https://t.me/+V7HSo1YNzkFkY2M1
    about: Join our Telegram group for real-time discussion
